upstreamProjects:
  Mule-runtime/api-annotations/master-SEPTEMBER
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
# TODO: Remove this to start using Maven 3.5.x after MULE-15966: The mule-revapi-extension tests fail using Maven version 3.5.x
mavenTool: M3
